### ISSUE TITLE
Difference between this repo and glove80-zmk-config-west?

### ISSUE THREAD

**Issue by rieje** [moergo-sc/glove80-zmk-config#17]
Dlsclaimer: noob. 

Curious what's the difference between glove80-zmk-config using Nix toolchain and [glove80-zmk-config-west](https://github.com/moergo-sc/glove80-zmk-config-west?tab=readme-ov-file)? Obviously the latter uses `west` toolchain but beyond that how would you determine which to use (even if it simply comes down to differences in toolchains if all else is equal)?

For example, ZMK/Zephyr uses `west` but AFAIK this repo is the official ZMK config repo for the Glove80. Is there any advantages to using `west` assuming [firmware is built via Docker](https://zmk.dev/docs/development/setup/docker) (I assume if built locally/natively sticking with the "unofficial" glove80-zmk-config-west reduces dependencies on the system). I would also think the other glove80-zmk-config-west repo using the same toolchain as ZMK might be better served as the default "official" repo? But it seems this repo is clearly more popular based on the stars count on the repo.

I assume you don't need to use NixOS to use Nix toolchain--are there any benefits to preferring Nix over west?

I realize it ultimately doesn't matter which toolchains you use as they both build the same thing and also a lot of this is probably opinionated--I'm just hoping to learn.

**Comment by chrisandreae** [comment]
The Nix toolchain makes it easier to install the required dependencies; they're all described by the nix package, and the version is pinned to a known good version. If you use a docker container for the dependencies, that reduces the advantage, but building the docker container may take a non-trivial amount of time itself.

It also builds slightly faster, and produces a combined image that can be uploaded to either half of the keyboard, rather than separate left and right images.

The actual resulting firmware is the same with both: the nix build builds the exact same cmake project, using the same dependencies as the west build (via a pin created using `west manifest --freeze`).
